# Static CRT: without this the binaries need vcruntime140.dll from the Visual
# C++ Redistributable, which is not part of a clean Windows install — a shared
# copy would fail to start with a missing-DLL error on a machine that has never
# had a C++ app installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
