[package]
name = "agent"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
core = { path = "../core" }
futures-util.workspace = true
reqwest.workspace = true
sandbox = { path = "../sandbox" }
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
viewer = { path = "../viewer" }
